# Classification of the sound with Machine Learning and visualization

<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Import-and-load-data" data-toc-modified-id="Import-and-load-data-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Import and load data</a></span></li><li><span><a href="#I---Binary-classification" data-toc-modified-id="I---Binary-classification-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>I - Binary classification</a></span><ul class="toc-item"><li><span><a href="#1)-k-Nearest-Neighbour-(k-NN)" data-toc-modified-id="1)-k-Nearest-Neighbour-(k-NN)-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>1) k Nearest Neighbour (k-NN)</a></span><ul class="toc-item"><li><span><a href="#Fitting" data-toc-modified-id="Fitting-2.1.1"><span class="toc-item-num">2.1.1&nbsp;&nbsp;</span>Fitting</a></span></li><li><span><a href="#Predicting" data-toc-modified-id="Predicting-2.1.2"><span class="toc-item-num">2.1.2&nbsp;&nbsp;</span>Predicting</a></span></li></ul></li><li><span><a href="#2)--Support-Vector-Machine-(SVM)" data-toc-modified-id="2)--Support-Vector-Machine-(SVM)-2.2"><span class="toc-item-num">2.2&nbsp;&nbsp;</span>2)  Support Vector Machine (SVM)</a></span><ul class="toc-item"><li><span><a href="#Fitting" data-toc-modified-id="Fitting-2.2.1"><span class="toc-item-num">2.2.1&nbsp;&nbsp;</span>Fitting</a></span></li><li><span><a href="#Predicting" data-toc-modified-id="Predicting-2.2.2"><span class="toc-item-num">2.2.2&nbsp;&nbsp;</span>Predicting</a></span></li></ul></li><li><span><a href="#3)-Random-Forest" data-toc-modified-id="3)-Random-Forest-2.3"><span class="toc-item-num">2.3&nbsp;&nbsp;</span>3) Random Forest</a></span><ul class="toc-item"><li><span><a href="#Fitting" data-toc-modified-id="Fitting-2.3.1"><span class="toc-item-num">2.3.1&nbsp;&nbsp;</span>Fitting</a></span></li><li><span><a href="#Predicting" data-toc-modified-id="Predicting-2.3.2"><span class="toc-item-num">2.3.2&nbsp;&nbsp;</span>Predicting</a></span></li></ul></li></ul></li><li><span><a href="#II---Multi-classification" data-toc-modified-id="II---Multi-classification-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>II - Multi classification</a></span><ul class="toc-item"><li><span><a href="#1)-k-Nearest-Neighbour-(k-NN)" data-toc-modified-id="1)-k-Nearest-Neighbour-(k-NN)-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>1) k Nearest Neighbour (k-NN)</a></span><ul class="toc-item"><li><span><a href="#Fitting" data-toc-modified-id="Fitting-3.1.1"><span class="toc-item-num">3.1.1&nbsp;&nbsp;</span>Fitting</a></span></li><li><span><a href="#Predicting" data-toc-modified-id="Predicting-3.1.2"><span class="toc-item-num">3.1.2&nbsp;&nbsp;</span>Predicting</a></span></li></ul></li><li><span><a href="#2)--Support-Vector-Machine-(SVM)" data-toc-modified-id="2)--Support-Vector-Machine-(SVM)-3.2"><span class="toc-item-num">3.2&nbsp;&nbsp;</span>2)  Support Vector Machine (SVM)</a></span><ul class="toc-item"><li><span><a href="#Fitting" data-toc-modified-id="Fitting-3.2.1"><span class="toc-item-num">3.2.1&nbsp;&nbsp;</span>Fitting</a></span></li><li><span><a href="#Predicting" data-toc-modified-id="Predicting-3.2.2"><span class="toc-item-num">3.2.2&nbsp;&nbsp;</span>Predicting</a></span></li></ul></li><li><span><a href="#3)-Random-Forest" data-toc-modified-id="3)-Random-Forest-3.3"><span class="toc-item-num">3.3&nbsp;&nbsp;</span>3) Random Forest</a></span><ul class="toc-item"><li><span><a href="#Fitting" data-toc-modified-id="Fitting-3.3.1"><span class="toc-item-num">3.3.1&nbsp;&nbsp;</span>Fitting</a></span></li><li><span><a href="#Predicting" data-toc-modified-id="Predicting-3.3.2"><span class="toc-item-num">3.3.2&nbsp;&nbsp;</span>Predicting</a></span></li></ul></li></ul></li><li><span><a href="#III---UMAP-(visualization)" data-toc-modified-id="III---UMAP-(visualization)-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>III - UMAP (visualization)</a></span></li></ul></div>

## Import and load data

In [1]:
from lib.File import File
from matplotlib import pyplot as plt
from data.loader import get_kasios_obs, get_obs, map_path
import numpy as np

from math import sqrt
import pandas as pd

In [2]:
# Loads files and makes conversion if necessary
df_all = get_obs(songs = True)
df_kasios = get_kasios_obs(songs = True)

Loading wav files...
Done.
Loading wav files...
Done.


In [3]:
# X = get_spectres(df_all) # Can be very long
# X.to_pickle("data/all_birds_freq.pickle") # Save to cache
X = pd.read_pickle("data/all_birds_freq.pickle") # Quicker to use cache

X.head()

1900.0    1910.0    1920.0    1930.0    1940.0    1950.0    1960.0  \
File ID                                                                         
402254  -0.777891 -0.398350 -0.014216 -0.855008  2.075899 -0.221931 -0.655440   
406171  -4.162661 -4.180349 -4.229848 -4.230835 -4.269890 -4.245544 -4.282711   
405901  -0.580728 -0.633019 -0.707576 -0.645468 -0.603866 -0.725716 -0.672938   
405548  -3.228091 -3.251748 -3.226915 -3.256686 -3.309930 -3.233574 -3.255813   
401782  -3.740562 -3.741388 -3.765818 -3.748055 -3.741544 -3.737901 -3.745398   

           1970.0    1980.0    1990.0    ...       5900.0    5910.0    5920.0  \
File ID                                  ...                                    
402254  -1.191778  0.585549  0.236256    ...     0.433391  0.306798 -1.075585   
406171  -4.257561 -4.243178 -4.282526    ...    -1.510778 -1.968467 -1.824303   
405901  -0.657233 -0.662175 -0.732691    ...    -0.300444 -0.458147 -0.586822   
405548  -3.283560 -3.262860 -3.241711    ...     7.121533  6.845443  6.915710   
401782  -3.741317 -3.749377 -3.750319    ...    -2.814041 -2.563670 -2.758136   

           5930.0    5940.0    5950.0    5960.0    5970.0    5980.0    5990.0  
File ID                                                                        
402254  -0.452546 -0.197668 -0.996424 -0.379281 -0.244899 -0.400091 -0.611824  
406171  -1.519034 -1.865900 -1.872201 -1.824038 -1.760304 -1.728515 -1.927553  
405901  -0.149122 -0.337683 -0.258401 -0.292191 -0.543218 -0.267194 -0.134089  
405548   6.386549  5.541339  4.538464  2.270188  0.207980  1.365019  3.283181  
401782  -2.482101 -2.802750 -2.417855 -2.802082 -2.927259 -2.785790 -2.790771  

[5 rows x 410 columns]

In [4]:
# X_kasios = get_spectres(df_kasios) # Can be very long
# X_kasios.to_pickle("data/kasios_birds_freq.pickle")
X_kasios = pd.read_pickle("data/kasios_birds_freq.pickle") # Quicker to use cache

X_kasios.head()

1900.0     1910.0     1920.0     1930.0     1940.0     1950.0  \
ID                                                                     
1   -3.529268  -3.329053  -3.513426  -3.523270  -3.362683  -3.481535   
2   -7.770975  -7.789180  -7.807659  -7.812153  -7.826096  -7.787444   
3  -10.823887 -10.997442 -10.907166 -10.946253 -10.891168 -10.957196   
4   -7.564831  -7.604928  -7.853263  -7.667681  -7.446895  -7.664611   
5   13.974970  13.250154  12.210977  12.134556  11.516458  11.235900   

       1960.0     1970.0     1980.0     1990.0    ...       5900.0    5910.0  \
ID                                                ...                          
1   -3.410325  -3.471149  -3.358526  -3.415705    ...    -3.231955 -3.377782   
2   -7.798715  -7.757632  -7.766777  -7.717729    ...     2.070107  1.240989   
3  -11.014657 -10.992509 -10.977279 -11.082591    ...    -7.309365 -7.188007   
4   -7.868092  -7.727359  -7.579639  -7.770928    ...    -6.860031 -6.743433   
5   10.998921  10.493838  10.029321   9.747640    ...    -3.994871 -3.862566   

      5920.0    5930.0    5940.0    5950.0    5960.0    5970.0    5980.0  \
ID                                                                         
1  -3.150853 -3.322742 -3.141581 -3.317984 -3.318084 -3.201280 -3.373770   
2   0.342733  1.253810 -0.095410  0.345641 -0.313179 -0.376685 -0.871546   
3  -8.339784 -6.470934 -6.471953 -7.001865 -8.281127 -7.377273 -7.894899   
4  -6.865163 -6.472720 -6.746985 -6.491604 -6.479721 -6.478345 -6.351524   
5  -3.970654 -4.009346 -3.824077 -4.031627 -3.842823 -3.883048 -4.091320   

      5990.0  
ID            
1  -3.249895  
2  -0.830625  
3  -7.307045  
4  -6.770690  
5  -3.786353  

[5 rows x 410 columns]

In [5]:
Y = df_all.English_name
Y_bin = df_all.English_name == "Rose-crested Blue Pipit"

In [6]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,recall_score,confusion_matrix

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.33)
X_bin_train, X_bin_test, y_bin_train, y_bin_test = train_test_split(X, Y_bin, test_size = 0.33)

## I - Binary classification

### 1) k Nearest Neighbour (k-NN)

#### Fitting

In [7]:
from sklearn.neighbors import KNeighborsClassifier

In [8]:
clf = KNeighborsClassifier(n_neighbors=2)
clf.fit(X_bin_train, y_bin_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=2, p=2,
           weights='uniform')

In [9]:
# Accuracy of the model
accuracy = clf.score(X_bin_test, y_bin_test)
print("Accuracy of the model: %s" % accuracy)

# Confusion matrix
y_bin_predict = clf.predict(X_bin_test)
print("Confusion matrix: \n%s" % confusion_matrix(y_bin_test, y_bin_predict))

Accuracy of the model: 0.9194729136163983
Confusion matrix: 
[[614   8]
 [ 47  14]]


#### Predicting

In [10]:
print("Binary classification with kNN \n")
y_kasios = clf.predict(X_kasios)
for i in range(len(y_kasios)):
    print("Kasios song n°%s : %s" % (i+1, y_kasios[i]))

Binary classification with kNN 

Kasios song n°1 : False
Kasios song n°2 : False
Kasios song n°3 : False
Kasios song n°4 : False
Kasios song n°5 : False
Kasios song n°6 : False
Kasios song n°7 : False
Kasios song n°8 : False
Kasios song n°9 : True
Kasios song n°10 : False
Kasios song n°11 : False
Kasios song n°12 : False
Kasios song n°13 : False
Kasios song n°14 : False
Kasios song n°15 : False


### 2)  Support Vector Machine (SVM)

#### Fitting

In [11]:
from sklearn import svm

In [12]:
x_list = np.linspace(2**-5, 2**5, 30)
accuracy_C = []
for x in x_list:
    model = svm.SVC(kernel='linear', C=x)
    model.fit(X_bin_train, y_bin_train)
    accuracy_C.append(model.score(X_bin_test, y_bin_test))
x = 0

# select the C with max accuracy
max_index = accuracy_C.index(max(accuracy_C))
C_chosed = x_list[max_index]

In [13]:
# we do the same thing for gamma
accuracy_gamma = []
for x in x_list:
    model = svm.SVC(kernel='linear', C=C_chosed, gamma=x)
    model.fit(X_bin_train, y_bin_train)
    accuracy_gamma.append(model.score(X_bin_test, y_bin_test))

# to find the C with the max accuracy
max_index = accuracy_gamma.index(max(accuracy_gamma))
gamma_chosed = x_list[max_index]  # the C that we will choose

In [14]:
# We can now define our SVM model
clf = svm.SVC(kernel='linear', C=C_chosed, gamma=gamma_chosed)
clf.fit(X_bin_train, y_bin_train)

SVC(C=0.03125, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=0.03125, kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [15]:
# Accuracy of the model
accuracy = clf.score(X_bin_test, y_bin_test)
print("Accuracy of the model: %s" % accuracy)

# Confusion matrix
y_bin_predict = clf.predict(X_bin_test)
print("Confusion matrix: \n%s" % confusion_matrix(y_bin_test, y_bin_predict))

Accuracy of the model: 0.8594436310395315
Confusion matrix: 
[[571  51]
 [ 45  16]]


#### Predicting

In [16]:
y_kasios = clf.predict(X_kasios)
for i in range(len(y_kasios)):
    print("Kasios song n°%s : %s" % (i+1, y_kasios[i]))

Kasios song n°1 : False
Kasios song n°2 : False
Kasios song n°3 : False
Kasios song n°4 : False
Kasios song n°5 : False
Kasios song n°6 : False
Kasios song n°7 : False
Kasios song n°8 : True
Kasios song n°9 : True
Kasios song n°10 : False
Kasios song n°11 : False
Kasios song n°12 : False
Kasios song n°13 : False
Kasios song n°14 : False
Kasios song n°15 : False


### 3) Random Forest 

#### Fitting

In [17]:
from sklearn.ensemble import RandomForestClassifier

/home/sajeevan/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d


In [18]:
clf = RandomForestClassifier(n_estimators=100, max_depth=7)

In [19]:
clf.fit(X_bin_train, y_bin_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=7, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

#### Predicting

In [20]:
y_pred_train = clf.predict(X_bin_train)
y_pred_test = clf.predict(X_bin_test)

In [21]:
print("Confusion matrix on trainning: (Overfit)")
print(confusion_matrix(y_bin_train, y_pred_train))

print("\n")

print("Confusion matrix on testing:")
print(confusion_matrix(y_bin_test, y_pred_test))

print()

Confusion matrix on trainning: (Overfit)
[[1257    2]
 [  22  103]]


Confusion matrix on testing:
[[616   6]
 [ 48  13]]



In [22]:
print(accuracy_score(y_bin_train, y_pred_train))
print("Accuracy: %s" % accuracy_score(y_bin_test,y_pred_test))

0.9826589595375722
Accuracy: 0.9209370424597365


In [23]:
y_kasios = clf.predict(X_kasios)

In [24]:
print("Classification with Random Forest \n")
for i in range(len(y_kasios)):
    print("Kasios song n°%s : %s"% (i+1, y_kasios[i]))

Classification with Random Forest 

Kasios song n°1 : False
Kasios song n°2 : False
Kasios song n°3 : False
Kasios song n°4 : False
Kasios song n°5 : False
Kasios song n°6 : False
Kasios song n°7 : False
Kasios song n°8 : False
Kasios song n°9 : False
Kasios song n°10 : False
Kasios song n°11 : False
Kasios song n°12 : False
Kasios song n°13 : True
Kasios song n°14 : False
Kasios song n°15 : False


## II - Multi classification

### 1) k Nearest Neighbour (k-NN)

#### Fitting

In [25]:
clf = KNeighborsClassifier(n_neighbors=2)
clf.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=2, p=2,
           weights='uniform')

In [26]:
# Accuracy of the model
accuracy = clf.score(X_test, y_test)
print("Accuracy of the model: %s" % accuracy)

# Confusion matrix
y_predict = clf.predict(X_test)
print("Confusion matrix: \n%s" % confusion_matrix(y_test, y_predict))

Accuracy of the model: 0.38653001464128844
Confusion matrix: 
[[15  1  0  1  0  0  1  0  3  1  0  0  0  0  0  0  0  0  0]
 [ 0  5  1  1  2  5  2  1  0  1  0  3  0  0  0  3  0  0  0]
 [ 0  1 19 10  2  3  5  0  0  1  0  1  0  0  1  1  2  0  0]
 [ 0  3  5 19  0  3  0  0  0  1  0  0  0  0  1  0  0  1  0]
 [ 1  3  1  1 16  2  1  3  0  1  1  3  0  0  0  1  0  1  0]
 [ 0  3  3  0  2 19  0  0  0  0  1  1  0  1  0  2  1  1  0]
 [ 0  3  2  2  1  4  7  0  0  1  1  2  0  0  0  0  0  0  0]
 [ 0  1  2  0  3  3  3  4  0  5  2  2  0  2  0  0  0  0  0]
 [ 0  3  2  2  0  1  2  0 17  1  0  0  0  0  0  0  0  0  0]
 [ 0  3  1  1  1  3  0  6  3 31  1  0  0  0  0  0  0  0  0]
 [ 5  3  8  4  1  1  1  0  0  2 29  0  1  1  6  0  2  2  3]
 [ 1  2  1  1  4 18  3  3  0  2  0  3  0  0  0  1  0  0  0]
 [ 2  1  2  7  0  2  2  0  1  1  3  1  1  0  0  1  0  0  0]
 [ 2  1  2  1  2  2  0  3  0  3  4  2  0  4  0  4  0  0  0]
 [ 0  0  0  5  0  1  0  0  0  0  4  0  0  0  1  0  0  1  1]
 [ 0  0  1  2  0  1  0  1  1  0  2  1 

#### Predicting

In [27]:
y_kasios = clf.predict(X_kasios)
for i in range(len(y_kasios)):
    print("Kasios song n°%s : %s" % (i+1, y_kasios[i]))

Kasios song n°1 : Bent-beak Riffraff
Kasios song n°2 : Blue-collared Zipper
Kasios song n°3 : Darkwing Sparrow
Kasios song n°4 : Darkwing Sparrow
Kasios song n°5 : Orange Pine Plover
Kasios song n°6 : Eastern Corn Skeet
Kasios song n°7 : Queenscoat
Kasios song n°8 : Lesser Birchbeere
Kasios song n°9 : Darkwing Sparrow
Kasios song n°10 : Orange Pine Plover
Kasios song n°11 : Canadian Cootamum
Kasios song n°12 : Orange Pine Plover
Kasios song n°13 : Queenscoat
Kasios song n°14 : Darkwing Sparrow
Kasios song n°15 : Scrawny Jay


### 2)  Support Vector Machine (SVM)

#### Fitting

In [28]:
x_list = np.linspace(2**-5, 2**5, 30)
accuracy_C = []
for x in x_list:
    model = svm.SVC(kernel='linear', C=x)
    model.fit(X_train, y_train)
    accuracy_C.append(model.score(X_test, y_test))
x = 0

# select the C with max accuracy
max_index = accuracy_C.index(max(accuracy_C))
C_chosed = x_list[max_index]

In [29]:
# we do the same thing for gamma

accuracy_gamma = []
for x in x_list:
    model = svm.SVC(kernel='linear', C=C_chosed, gamma=x)
    model.fit(X_train, y_train)
    accuracy_gamma.append(model.score(X_test, y_test))

# to find the C with the max accuracy
max_index = accuracy_gamma.index(max(accuracy_gamma))
gamma_chosed = x_list[max_index]  # the C that we will choose

In [30]:
# We can now define our SVM model
clf = svm.SVC(kernel='linear', C=C_chosed, gamma=gamma_chosed)
clf.fit(X_train, y_train)

SVC(C=0.03125, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=0.03125, kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [31]:
# Accuracy of the model
accuracy = clf.score(X_test, y_test)
print("Accuracy of the model: %s" % accuracy)

# Confusion matrix
y_predict = clf.predict(X_test)
print("Confusion matrix: \n%s" % confusion_matrix(y_test, y_predict))

Accuracy of the model: 0.42020497803806733
Confusion matrix: 
[[15  0  0  1  0  0  2  0  3  1  0  0  0  0  0  0  0  0  0]
 [ 0  2  3  0  1  3  2  0  1  0  0  3  0  1  0  4  4  0  0]
 [ 1  2 21  4  0  0  4  1  0  0  6  1  0  1  1  1  1  0  2]
 [ 3  0  4 12  0  1  0  0  1  0  2  0  1  1  3  0  0  3  2]
 [ 0  0  2  1  5  1  1  8  0  2  0  5  1  0  0  2  7  0  0]
 [ 0  1  3  0  1 15  0  3  0  3  0  1  1  0  0  2  3  1  0]
 [ 0  0  3  0  0  1 14  0  0  0  0  2  0  1  0  0  2  0  0]
 [ 0  4  1  1  2  6  0  4  0  3  0  2  0  0  0  1  3  0  0]
 [ 0  0  1  0  0  1  1  0 20  2  1  0  0  0  0  0  1  0  1]
 [ 0  0  1  0  1  4  0  3  3 35  0  0  0  0  0  0  2  1  0]
 [ 2  4  3  3  0  0  1  0  0  1 35  2  3  0  3  1  1  4  6]
 [ 0  3  3  0  1  6  4  6  0  3  1  6  0  0  1  0  5  0  0]
 [ 2  0  4  4  0  3  1  0  1  0  1  1  1  0  2  1  1  1  1]
 [ 1  3  1  1  3  1  1  2  0  2  2  2  0  2  1  4  3  0  1]
 [ 0  0  1  4  0  1  0  0  0  0  2  0  0  0  2  0  0  1  2]
 [ 1  0  0  1  0  2  0  0  0  0  6  0 

#### Predicting

In [32]:
y_kasios = model.predict(X_kasios)
for i in range(len(y_kasios)):
    print("Kasios song n°%s : %s" % (i+1, y_kasios[i]))

Kasios song n°1 : Bent-beak Riffraff
Kasios song n°2 : Rose-crested Blue Pipit
Kasios song n°3 : Darkwing Sparrow
Kasios song n°4 : Darkwing Sparrow
Kasios song n°5 : Broad-winged Jojo
Kasios song n°6 : Green-tipped Scarlet Pipit
Kasios song n°7 : Scrawny Jay
Kasios song n°8 : Lesser Birchbeere
Kasios song n°9 : Darkwing Sparrow
Kasios song n°10 : Bombadil
Kasios song n°11 : Bent-beak Riffraff
Kasios song n°12 : Orange Pine Plover
Kasios song n°13 : Rose-crested Blue Pipit
Kasios song n°14 : Darkwing Sparrow
Kasios song n°15 : Orange Pine Plover


### 3) Random Forest 

#### Fitting

In [33]:
clf = RandomForestClassifier(n_estimators=100, max_depth=7)
clf.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=7, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

#### Predicting

In [34]:
y_pred_train = clf.predict(X_train)
y_pred_test = clf.predict(X_test)

In [35]:
print("Confusion matrix on trainning: (Overfit)")
print(confusion_matrix(y_train, y_pred_train))

print("\n")

print("Confusion matrix on testing:")
print(confusion_matrix(y_test, y_pred_test))

print()

Confusion matrix on trainning: (Overfit)
[[ 42   0   0   0   0   1   0   0   3   0   1   0   0   0   0   2   0   0
    0]
 [  0  14   3   0   0   8   4   0   0   2   4   1   0   0   0   0   7   0
    0]
 [  0   0  78   1   0   1   1   1   0   1   5   0   0   0   0   0   3   0
    0]
 [  1   0   2  48   0   0   0   0   1   0   0   0   0   0   1   0   1   4
    2]
 [  0   0   1   0  24   3   1   2   1   2   3   0   0   0   0   0   8   1
    1]
 [  0   0   2   0   0  50   1   0   2   1   2   3   0   0   0   0   9   0
    0]
 [  1   0   1   1   1   1  50   1   1   0   1   1   0   0   0   0   4   0
    0]
 [  0   0   2   0   0   7   4  35   0   3   1   2   0   0   0   0   7   0
    0]
 [  1   0   0   0   0   1   0   0  56   1   0   0   0   0   0   0   0   0
    0]
 [  0   0   1   0   0   1   0   0   1  94   1   1   0   0   0   0   1   0
    0]
 [  0   0   2   2   0   2   0   0   3   0 136   0   0   0   0   0   0   0
    1]
 [  0   0   3   0   1   6   4   1   0   0   0  30   0   0   0   2   

In [36]:
print(accuracy_score(y_train, y_pred_train))
print("Accuracy: %s" % accuracy_score(y_test,y_pred_test))

0.7630057803468208
Accuracy: 0.4904831625183016


In [37]:
y_kasios = clf.predict(X_kasios)

In [38]:
print("Classification with Random Forest \n")
for i in range(len(y_kasios)):
    print("Kasios song n°%s : %s"% (i+1, y_kasios[i]))

Classification with Random Forest 

Kasios song n°1 : Bent-beak Riffraff
Kasios song n°2 : Rose-crested Blue Pipit
Kasios song n°3 : Bombadil
Kasios song n°4 : Darkwing Sparrow
Kasios song n°5 : Orange Pine Plover
Kasios song n°6 : Green-tipped Scarlet Pipit
Kasios song n°7 : Scrawny Jay
Kasios song n°8 : Lesser Birchbeere
Kasios song n°9 : Rose-crested Blue Pipit
Kasios song n°10 : Orange Pine Plover
Kasios song n°11 : Queenscoat
Kasios song n°12 : Orange Pine Plover
Kasios song n°13 : Rose-crested Blue Pipit
Kasios song n°14 : Darkwing Sparrow
Kasios song n°15 : Orange Pine Plover


## III - UMAP (visualization)

In [7]:
import umap

embedding = umap.UMAP(n_neighbors=10).fit_transform(pd.concat([X, X_kasios]))

/home/guillaume/anaconda3/lib/python3.6/site-packages/sklearn/metrics/pairwise.py:257: RuntimeWarning: invalid value encountered in sqrt
  return distances if squared else np.sqrt(distances, out=distances)


In [8]:
from bokeh.plotting import figure, show, output_notebook
from bokeh.models import HoverTool, ColumnDataSource, CategoricalColorMapper
from bokeh.palettes import Category20
from bokeh.models import Legend

output_notebook()

Loading BokehJS ...

In [9]:
df_umap = pd.DataFrame(embedding, columns=('x', 'y'))
df_umap['specie'] = [specie for specie in Y] + ['Kasios Test Bird' for i in range(15)]
df_umap['kasios_index'] = [None for i in Y] + [i for i in range(1, 16)]


plot_figure = figure(
    title='UMAP projection of the birds songs',
    plot_width=800,
    plot_height=600,
    tools=('pan, wheel_zoom, reset'), 
    toolbar_location='above'
)

color_mapping = CategoricalColorMapper(factors=df_umap['specie'].unique(),
                                       palette=Category20[20])

plot_figure.add_tools(HoverTool(tooltips="""
<div>
    <div>
        <span style='font-size: 13px; color: #224499'>Specie:</span>
        <span style='font-size: 13px'>@specie</span>
    </div>
</div>
"""))

legend_items = []

for specie in df_umap['specie'].unique():
    datasource = ColumnDataSource(df_umap.loc[df_umap['specie'] == specie])
    if specie == 'Kasios Test Bird':
        c = plot_figure.circle('x', 'y', source=datasource, color='black',
                               line_alpha=0.7, fill_alpha=0.7, size=20)

        plot_figure.text('x', 'y', text='kasios_index', x_offset=-5, y_offset=8,
                         source=datasource, text_font_size='10pt', text_color='white')
    else:
        c = plot_figure.circle('x', 'y', source=datasource,
                               color=dict(field='specie', transform=color_mapping),
                               line_alpha=0.6, fill_alpha=0.6, size=5)
        
    legend_items.append((specie, [c]))
    

legend = Legend(items=legend_items, location=(30, 50))
legend.click_policy = 'hide'
plot_figure.add_layout(legend, 'right')

show(plot_figure)

In [10]:
plot_figure = figure(
    title='UMAP projection of the birds songs',
    plot_width=800,
    plot_height=600,
    tools=('pan, wheel_zoom, reset'), 
    toolbar_location='above'
)

color_mapping = CategoricalColorMapper(factors=df_umap['specie'].unique(),
                                       palette=Category20[20])

plot_figure.add_tools(HoverTool(tooltips="""
<div>
    <div>
        <span style='font-size: 13px; color: #224499'>Specie:</span>
        <span style='font-size: 13px'>@specie</span>
    </div>
</div>
"""))

legend_items = []

for specie in df_umap['specie'].unique():

    datasource = ColumnDataSource(df_umap.loc[df_umap['specie'] == specie])
    if specie == 'Kasios Test Bird':
        c = plot_figure.circle('x', 'y', source=datasource, color='black',
                               line_alpha=0.7, fill_alpha=0.7, size=20)

        plot_figure.text('x', 'y', text='kasios_index', x_offset=-5, y_offset=8,
                         source=datasource, text_font_size='10pt', text_color='white')
    else:
        c = plot_figure.circle('x', 'y', source=datasource,
                               color=dict(field='specie', transform=color_mapping),
                               muted_color=dict(field='specie', transform=color_mapping),
                               line_alpha=0.6, fill_alpha=0.6, size=5, muted_alpha=0.1)
        
    legend_items.append((specie, [c]))
    if specie != 'Rose-crested Blue Pipit': 
        c.muted = True
    
legend = Legend(items=legend_items, location=(30, 50))
legend.click_policy = 'hide'
plot_figure.add_layout(legend, 'right')

show(plot_figure)